# Generated by Django 4.0.7 on 2022-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caffes', '0002_caffe_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caffe',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
