# Generated by Django 4.0.7 on 2022-10-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caffes', '0003_alter_caffe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caffe',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
