# Generated by Django 4.0.7 on 2022-10-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caffes', '0005_alter_caffe_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='caffe',
            name='description',
            field=models.TextField(default='No description yet)'),
        ),
    ]
