# Generated by Django 4.0.7 on 2022-10-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caffes', '0006_caffe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='caffe',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caffe',
            name='longtitude',
            field=models.FloatField(default=0.0),
        ),
    ]
