# Generated by Django 4.0.7 on 2022-10-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caffes', '0007_caffe_latitude_caffe_longtitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('caffe_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='caffes.caffe')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
