# Generated by Django 4.0.7 on 2022-10-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caffes', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
